# Copyright 2017-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=8

CRATES="
adler32-1.0.4
ansi_term-0.11.0
assert_cmd-1.0.1
atty-0.2.14
bitflags-1.2.1
capstone-0.7.0
capstone-sys-0.11.0
cc-1.0.52
cfg-if-0.1.10
clap-2.33.3
crc32fast-1.2.0
difference-2.0.0
doc-comment-0.3.3
escargot-0.5.0
flate2-1.0.14
hermit-abi-0.1.12
itoa-0.4.5
lazy_static-1.4.0
libc-0.2.69
log-0.4.8
memmap-0.7.0
miniz_oxide-0.3.6
object-0.21.1
predicates-1.0.4
predicates-core-1.0.0
predicates-tree-1.0.0
proc-macro2-1.0.12
quote-1.0.4
ryu-1.0.4
serde-1.0.110
serde_derive-1.0.110
serde_json-1.0.53
strsim-0.8.0
syn-1.0.19
textwrap-0.11.0
treeline-0.1.0
unicode-width-0.1.7
unicode-xid-0.2.0
vec_map-0.8.2
wait-timeout-0.2.0
wasmparser-0.57.0
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="decode x86 binaries and print out which instruction set extensions they use"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/pkgw/elfx86exts"
SRC_URI="
	https://github.com/pkgw/elfx86exts/archive/refs/tags/${PN}@${PV}.tar.gz
	$(cargo_crate_uris ${CRATES})
"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""

S=${WORKDIR}/${PN}-${P}
